# Generated by Django 4.0.6 on 2022-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('regular', "Regular - Can't delete members"), ('admin', 'Admin - Can delete members')], max_length=10)),
            ],
        ),
    ]
