# Generated by Django 4.0.6 on 2022-07-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
